app:
  authorization:
    type: Bearer
  jwtExpirationsMs: 86400000
  jwtSecret: HRlELXqpSB
spring:
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
  datasource:
    username: ${JDBC_DATABASE_USERNAME:postgres}
    password: ${JDBC_DATABASE_PASSWORD:postgres}
    url: ${JDBC_DATABASE_URL:jdbc:postgresql://localhost:5432/voccards}
    driverClassName: org.postgresql.Driver
  jpa:
    show-sql: true
server:
  port: 8070
